parameters:
    imocontrol_m3_admin.listener.request.class: IMOControl\M3\AdminBundle\Listener\RequestListener

services:
    imocontrol.admin.listener.request:
        class: %imocontrol_m3_admin.listener.request.class%
        arguments: [ @service_container ]
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }